const burger = document.querySelector('.burger')
const headerMenu = document.querySelector('.header__menu')
const headerMenuLink = document.querySelector('.header__menu-link')
const body = document.querySelector('body')
const bur = document.querySelector('.bur')
burger.addEventListener('click', () => {
    headerMenu.classList.toggle('active')
    body.classList.toggle('active')
    bur.classList.toggle('active')
})